In [1]:
                                       #SWAPPING
def swap(nList):
    size = len(nList)
    temp = nList[0]
    nList[0]=nList[size-1]
    nList[size-1]=temp
    return nList
nList = [12,35,9,56,24]
print(swap(nList))

[24, 35, 9, 56, 12]


In [2]:
def swap(nList):
    nList[0],nList[-1]=nList[-1],nList[0]
    return nList
nList=[1,2,3,4]
print(swap(nList))

[4, 2, 3, 1]


In [3]:
def swap(nList):
    start,*middle,end = nList
    nList = (end,*middle,start)
    return nList
nList = [1,2,3,4]
print(swap(nList))

(4, 2, 3, 1)


In [4]:
#Taking array input
a =[]
b = int(input("Enter the number of elements : "))
for i in range(b):
    ele = int(input())
    a.append(ele)
print(a)

Enter the number of elements : 5
1
2
3
4
5
[1, 2, 3, 4, 5]


In [10]:
#Taking array input with white space of multiple array inside
a = []
b = int(input("Number of elements : "))
for i in range(b):
    ele = list(map(int,input().split()))
    a.append(ele)
print(a)

Number of elements : 3
123
1 2 3
1
[[123], [1, 2, 3], [1]]


In [8]:
#Taking array input with white space
b = int(input("Number of elements : "))
a = list(map(int,input().split()))
if(len(a)==b):
    print(a)
else:
    print("oops")

Number of elements : 5
1 2 3 4 5
[1, 2, 3, 4, 5]


In [8]:
#Python program to swap two elements in a list
def swapby(nList,a,b):
    nList[a],nList[b]=nList[b],nList[a]
    return nList
nList = list(map(int,input().split()))
print("List : ",nList)
a = int(input("Enter the first element : "))
b = int(input("Enter the second element : "))
print(swapby(nList,a-1,b-1))

1 2 3 4 5
List :  [1, 2, 3, 4, 5]
Enter the first element : 1
Enter the second element : 5
[5, 2, 3, 4, 1]


In [14]:
                                       #Palindrome/Symmetrical
string =input("Enter the string : ")
half = int(len(string)/2)

if len(string)%2 == 0:
    first_str = string[:half]
    second_str = string[half:]
else:
    first_str = string[:half]
    second_str = string[half+1:]

if first_str == second_str:
    print("Symmetrical")
else:
    print("Not Symmetrical")

if first_str == second_str[::-1]:
    print("Palindrome")
else:
    print("Not Palindrome")


Enter the string : khokho
Symmetrical
Not Palindrome


In [15]:
                                        #Reversing a string
a = "Hello I am Siva"
b = a.split()
c = b[::-1]
d = ' '.join(c)
print(d)

Siva am I Hello


In [16]:
                                        #Removing an element
a = "willingness"

print("removed L : ",a.replace('l',''))
print("removed only one i : ",a.replace('i','',1))

removed L :  wiingness
removed only one i :  wllingness


In [19]:
                                #Print even len string
l = []
a = "This is a string"
b = a.split()
for i in b:
    if len(i)%2==0:
        l.append(i)
print(' '.join(l))

This is string


In [22]:
                                          #Size of Tuple
import sys
a = ("A",1,"B",2,"C",3,"D",4)
print("Size is : ",str(sys.getsizeof(a)) + " Bytes")

Size is :  104 Bytes


In [24]:
                                    #Max&Min K element in Tuple
a = (5,20,3,7,6,8)
print("Orginal Tuple : ",str(a))
K=1

b = list(a)
temp = sorted(b)
res = [temp[:K],temp[-K:]]
print(res)

Orginal Tuple :  (5, 20, 3, 7, 6, 8)
[[3], [20]]


In [26]:
                                   #Sum of elements in a Tuple
a = ([7,8],[9,1],[10,7])
print("Orginal Tuple : ",str(a))

summ = sum(list(map(sum,list(a))))
print(summ)

Orginal Tuple :  ([7, 8], [9, 1], [10, 7])
42


In [27]:
a = (7,8,9,1,10,7)
print("Orginal Tuple : ",str(a))

summ = sum(list(a))
print(summ)

Orginal Tuple :  (7, 8, 9, 1, 10, 7)
42


In [28]:
#Sum of elements in a list
a = [5,5,5,5]
print("List : ",a)
summ = sum(a)
print(summ)

List :  [5, 5, 5, 5]
20


In [9]:
                          #Row-Wise addition of element into Tuple
lis = [[('q',1),('w',2)],[('e',3)],[('r',4),('t',5),('y',6)]]
print(str(lis))
rep = [3,2,1]

res = [[sub + (rep[idx],) for sub in val] for idx,val in enumerate(lis)]
print(res)

[[('q', 1), ('w', 2)], [('e', 3)], [('r', 4), ('t', 5), ('y', 6)]]
[[('q', 1, 3), ('w', 2, 3)], [('e', 3, 2)], [('r', 4, 1), ('t', 5, 1), ('y', 6, 1)]]


In [32]:
                         #List of tuples having number and its cube
list1 = [1,2,5,6]
res = [(val,pow(val,3)) for val in list1]
print(res)

[(1, 1), (2, 8), (5, 125), (6, 216)]


In [10]:
                         #Cube of each element in a list
list1 = [1,2,5,6]
res = []
for i in list1:
    res.append(pow(i,3))
print(res)

[1, 8, 125, 216]


In [15]:
                         #Sort Python Dictionaries by Key
myDic = {"b":4,"e":6,"a":2,"c":3,"d":5}
myKeys = list(myDic.keys())
myKeys.sort()
res = {i:myDic[i] for i in myKeys}
print(res)

{'a': 2, 'b': 4, 'c': 3, 'd': 5, 'e': 6}


In [27]:
                    #Dictionary with keys having multiple inputs
dic = {}

x,y,z = 10,20,30
dic[x,y,z] = x+y-z

x,y,z = 5,2,4
dic[x,y,z]=x+y-z

print(dic)

{(10, 20, 30): 0, (5, 2, 4): 3}


In [32]:
                           #Sum of values in dictionary
def addition(dict):
    sum=0
    for i in dict.values():
        sum += i 
    return sum

dict = {'a':100,'b':200,'c':300}
print("Sum : ",addition(dict))

Sum :  600


In [112]:
                              #Size of a Dictionary
import sys
dict = {'a':100,'b':200,'c':300}
print(str(sys.getsizeof(dict))+" Bytes")

232 Bytes


In [33]:
                              #Iterate over a set
a = set("siva")
for i in a:
    print(i)

v
s
i
a


In [37]:
                            #Removing values 1 by 1 in set
def Remove(a):
    while a:
        a.pop()
        print(a)
a = set([12,10,13,15,8,9])
Remove(a)

{9, 10, 12, 13, 15}
{10, 12, 13, 15}
{12, 13, 15}
{13, 15}
{15}
set()


In [38]:
                             #Checks for commmon value in list
def data(a,b):
    result = False
    for i in a:
        for j in b:
            if(i==j):
                result = True
                return result
    return result
    
a = [1,2,3,4,5]
b = [5,6,7,8,9]
print(data(a,b))

a = [1,2,3,4,5]
b = [6,7,8,9,10]
print(data(a,b))

True
False


In [2]:
                        #Assigning rows to matrix first row element
nList = [[1,2,3],[4,5,6],[7,8,9],[3,2,1]]
print("Orginal List : ", str(nList))

res = {nList[0][ele]:nList[ele+1] for ele in range(len(nList)-1)}
print(res)

Orginal List :  [[1, 2, 3], [4, 5, 6], [7, 8, 9], [3, 2, 1]]
{1: [4, 5, 6], 2: [7, 8, 9], 3: [3, 2, 1]}


In [52]:
                        #Matrix Addition & Subtraction
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[4,5],[6,7]])

print("First Matrix : ")
print(A)
print("\n")
print("Second Matrix : ")
print(B)

print("Added Matrix : ")
print(np.add(A,B))
print("\n")
print("Subtracted Matrix : ")
print(np.subtract(A,B))


First Matrix : 
[[1 2]
 [3 4]]


Second Matrix : 
[[4 5]
 [6 7]]
Added Matrix : 
[[ 5  7]
 [ 9 11]]


Subtracted Matrix : 
[[-3 -3]
 [-3 -3]]


In [4]:
                         #Group Similar elements into matrix
from itertools import groupby
a = [1,3,5,1,3,2,5,4,2]
print("Orginal List : ", str(a))

res = [list(val) for key,val in groupby(sorted(a))]
print(res)

Orginal List :  [1, 3, 5, 1, 3, 2, 5, 4, 2]
[[1, 1], [2, 2], [3, 3], [4], [5, 5]]


In [13]:
                        #NXN Square Matrix, where opposite corner is even
import itertools
def mat(n):
    temp = itertools.count(1)
    l = [[next(temp) for i in range(n)] for i in range(n)]
    
    if n%2==0:
        for i in range(0,len(l)):
            l[i][:]=l[i][::-1]
    for i in range(n):
        for j in range(n):
            print(l[i][j],end=' ')
        print()
n=4
mat(n)

4 3 2 1 
8 7 6 5 
12 11 10 9 
16 15 14 13 


In [69]:
                                 #Matrix Multiplication
import numpy as np

X = np.array([[1,2,3],[4,5,6],[7,8,9]])
Y =np.array([[9,8,7],[6,5,4],[3,2,1]])

print(np.multiply(X,Y))

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [14]:
                            #Patamater name from a function
def fun(a,b):
    return a**b
import inspect
print(inspect.signature(fun))

(a, b)


In [71]:
                                 #Power of numbers
a = int(input("Number : "))
b = int(input("Power : "))
print(pow(a,b))

Number : 2
Power : 3
8


In [18]:
                                  #Sorting in class
class GFG:
    def __init__(self,a,b):
        self.a=a
        self.b=b
    def __repr__(self):
        return str((self.a,self.b))

gfg = [GFG("c",1),GFG("b",3),GFG("e",2),GFG("a",4),GFG("g",3)]

print(sorted(gfg, key=lambda x : x.b))

[('c', 1), ('e', 2), ('b', 3), ('g', 3), ('a', 4)]


In [83]:

class GFG:
    def __init__(self,a,b):
        self.a=a
        self.b=b
    def __repr__(self):
        return str((self.a,self.b))
gfg = [GFG("c",1),GFG("b",3),GFG("e",2),GFG("a",4),GFG("g",3)]
print(sorted(gfg, key=lambda x: x.a.lower()))

[('a', 4), ('b', 3), ('c', 1), ('e', 2), ('g', 3)]


In [22]:
                                #Lambda if-else Statement
square = lambda x : pow(x,2) if(x>0) else None
print(square(4))

16


In [27]:
                         #Sorting string from reverse using order defined from another string
def sortby(a,b):
    a = list(a)
    myDic = {a[i]:i for i in range(len(a))}
    b = list(b)
    b.sort(key = lambda ele : myDic[ele])
    b.reverse()
    new_b = ''.join(b)
    return new_b
if __name__=="__main__":
    a = "iudcba"
    b = "bacd"
    print(sortby(a,b))   

abcd


In [30]:
                                #Fibonacci Series
from functools import reduce
fib = lambda n : reduce(lambda x,_ : x+[x[-1]+x[-2]],range(n-2),[0,1])
print(fib(5))

[0, 1, 1, 2, 3]


In [31]:
                              #Odd & Even number in list
list1 = [1,2,3,4,5,6,7,8,9]
a,b = 0,0
for num in list1:
    if num%2==0:
        a+=1
    else:
        b+=1
print("Even : ",a)
print("Odd : ",b)

Even :  4
Odd :  5


In [3]:
                              #Half Diamond Star Formation 
def diamond(n):
    for i in range(n):
        for j in range(0,i+1):
            print("*",end='')
        print()
    for i in range(1,n):
        for j in range(i,n):
            print("*",end='')
        print()
n=5
diamond(n)

*
**
***
****
*****
* * * * 
* * * 
* * 
* 


In [35]:
                              #Left Angle Triangle Pattern
def leftangle(n):
    for i in range(n):
        print(" "*(n-i)+"*"*i)
n = 5
leftangle(n)

     
    *
   **
  ***
 ****


In [64]:
                                #Triangle Pattern
def triangle(n):
    k = n-1
    for i in range(0,n):
        for j in range(0,k):
            print(end=" ")
        k = k-1
        for j in range(0,i+1):
            print("* ",end="")
        print()
n = 5
triangle(n)

    * 
   * * 
  * * * 
 * * * * 
* * * * * 


In [16]:
def diamond(n):
    k = n-1
    for i in range(0,n):
        for j in range(0,k):
            print(end=" ")
        k = k-1
        for j in range(0,i+1):
            print("* ",end="")
        print()
    for i in range(1,n):
        a = print(" "*i+"* "*(n-i))
n = 5
diamond(n)

    * 
   * * 
  * * * 
 * * * * 
* * * * * 
 * * * * 
  * * * 
   * * 
    * 


In [30]:
                                    #Print Digit Pattern
n = 41325
a = str(n)
for i in a:
    for j in range(int(i)):
        print("*",end="")
    print()

****
*
***
**
*****


In [33]:
                                    #Current Time using PYTZ
from datetime import *
import pytz

tz_IND = pytz.timezone('Asia/Kolkata')
dt_IND = datetime.now(tz_IND)
print('TIme : ',dt_IND.strftime("%H:%M:%S"))

TIme :  12:16:59


In [37]:
import time
TIme = time.localtime()
currentTime = time.strftime("%H:%M:%S",Time)
print(currentTime)

12:24:57


In [40]:
                                #Date of today&yesterday
from datetime import date
from datetime import timedelta

today = date.today()
print("Today's Date : ", today)

yesterday = today - timedelta(days=1)
print("Yesterday's Date: ",yesterday)

Today's Date :  2023-01-26
Yesterday's Date:  2023-01-25


In [4]:
import random
class flashcard:
    def __init__(self):
        self.fruits = {"apple":"red","orange":"orange","banana":"yellow"}
    def quiz(self):
        while True:
            fruit,color = random.choice(list(self.fruits.items()))
            print("What is the colour of {}".format(fruit))
            a = input()
            if(a.lower()==color):
                print("Correct")
            else:
                print("Wrong")
            option = int(input("Enter 0 to restart the quiz : "))
            if(option):
                break
print("Welcome to the quiz")
flashcard().quiz()

Welcome to the quiz
What is the colour of banana
yellow
Correct
Enter 0 to restart the quiz : 0
What is the colour of banana
yellow
Correct
Enter 0 to restart the quiz : 0
What is the colour of orange
orange
Correct
Enter 0 to restart the quiz : 1


In [5]:
                     #Regex - Regular Expression to find matching string
import re
text = "Hello World"
x = re.search("Hello",text)
if x:
    print("There is a match")
else:
    print("There is no match")

There is a match


In [14]:
                     #To find content inside html tag
import re
html= '<b>hello guys</b> i <b> am siva</b>'
print("Orginal string",str(html))

tag = "b"
reg = "<"+tag+">"+"(.*?)</"+tag+">"
res = re.findall(reg,html)
print("Result : ",res)

Orginal string <b>hello guys</b> i <b> am siva</b>
Result :  ['hello guys', ' am siva']


In [32]:
                           #RE for checking match
import re
def check(str,pattern):
    if re.search(pattern,str):
        print("Matches")
    else:
        print("Not a match")
pattern = re.compile("^[123456]+$")
check('125',pattern)
check('127',pattern)

Matches
Not a match


In [58]:
                                     #Linear Search
def lsearch(a,b):
    for i in a:
        if i==b:
            print("Present")
            return
    print("Not present")
    return
a = [1,2,3,4,5]
b = int(input())
lsearch(a,b)

5
Present


In [2]:
                                    #Binary Search
def bsearch(a,x):
    low = 0
    high = len(a) - 1
    mid = 0
    while low<=high:
        mid = (high+low)//2
        
        if a[mid]<x:
            low = mid+1
        elif a[mid]>x:
            high = mid-1
        else:
            return mid
    return -1

a = [1,2,3,4,5]
x = int(input("Enter : "))
result = bsearch(a,x)

if result!=-1:
    print("Element Present in index ",str(result))
else:
    print("Element not present")
   

Enter : 6
Element not present


In [7]:
                                        # Anagram                
def ana(a,b):
    if sorted(a)==sorted(b):
        return True
    return False
def search(txt,wrd):
    t=0
    lt=len(txt)
    lw=(len(wrd))
    
    for i in range(lt-lw+1):
        if ana(txt[i:i+lw],wrd):
            t=1
            print("Found in : ",i)
    if t==0:
        print("Anagram not found")
txt = "The cat is actually a cat"
wrd = input("Enter the word : ")
search(txt,wrd)                                                                                                    

Enter the word : cat
Found in :  4
Found in :  11
Found in :  22


In [10]:
                                          #Bubble Sort
def bubblesort(a):
    n = len(a)
    swapped = False
    
    for i in range(n-1):
        for j in range(0,n-i-1):
            
            if a[j]>a[j+1]:
                swapped = True
                a[j],a[j+1] = a[j+1],a[j]
        if not swapped:
            return

a = [64,34,25,12,22,11,90]
bubblesort(a)

print("Sorted array is : ")
for i in range(len(a)):
    print(a[i], end=" ")
               

Sorted array is : 
11 12 22 25 34 64 90 

In [40]:
                                     #MergeSort on Linked List
class Node:
    def __init__(self,data):
        self.data = data
        self.next = None
        
def takeInput():
    inputList = [int(ele) for ele in input().strip().split()]
    head = None
    tail = None
    
    for ele in inputList:
        if ele == -1:
            break
        newNode = Node(ele)
        if head is None:
            head = newNode
            tail = newNode
        else:
            tail.next = newNode
            tail = newNode
    return head

def merge2LL(head1,head2):
    final_head = None
    final_tail = None
    if (head1 is None) and (head2 is None):
        return head1
    if (head1 is not None) and (head2 is None):
        return head1
    if (head1 is None) and (head2 is not None):
        return head2
    if head1.data < head2.data:
        final_head = head1
        final_tail = head1
        head1 = head1.next
    else: 
        final_head = head2
        final_tail = head2
        head2 = head2.next
    
    while (head1 is not None) and (head2 is not None):
        if head1.data < head2.data:
            final_tail.next = head1
            final_tail = final_tail.next
            head1 = head1.next
        else:
            final_tail.next = head2
            final_tail = final_tail.next
            head2 = head2.next
            
    if head1 is not None:
        final_tail.next = head1
    else:
        final_tail.next = head2
    return final_head

def mergeSort(head):
    if head.next is None:
        return head
    
    slow = head
    fast = head
    mid = None
    
    if (fast.next is not None) and (fast.next.next is not None):
        slow = slow.next
        fast = fast.next.next
    if slow is not None:
        mid = slow
    
    head1 = head
    head2 = mid.next
    mid.next = None
    left = mergeSort(head1)
    right = mergeSort(head2)
    finalHead = merge2LL(left,right)
    return finalHead
    
def printLL(head):
    while head is not None:
        print(head.data,end=" --> ")
        head = head.next
    print("None")
    
li = takeInput()
mergeSort(li)
printLL(li)

15 10 5 20 3 2
15 --> 20 --> None


In [3]:
                                         #Reversing Stack
class Stack:
    def __init__(self):
        self.Elements = []
    def push(self,value):
        self.Elements.append(value)
    def pop(self):
        return self.Elements.pop()
    def empty(self):
        return self.Elements == []
    def show(self):
        for value in reversed(self.Elements):
            print(value)

def BottomInsert(s,value):
    if s.empty():
        s.push(value)
    else:
        popped = s.pop()
        BottomInsert(s,value)
        s.push(popped)

def Reverse(s):
    if s.empty():
        pass
    else:
        popped = s.pop()
        Reverse(s)
        BottomInsert(s,popped)

stk = Stack()
n = int(input("Size of Stack : "))
for i in range(0,n):
    a = int(input("Enter Element : "))
    stk.push(a)
    
print("Orginal Stack is : ")
stk.show()
print("Reversed Stack is : ")
Reverse(stk)
stk.show()

Size of Stack : 5
Enter Element : 1
Enter Element : 2
Enter Element : 3
Enter Element : 4
Enter Element : 5
Orginal Stack is : 
5
4
3
2
1
Reversed Stack is : 
1
2
3
4
5


In [4]:
                                     #EdgeCovered Calculator
import math

def edgeCover(n):
    result = 0
    result = math.ceil(n/2.0)
    return result

if __name__ == "__main__":
    n = int(input("Enter Number of Vertices : "))
    print(int(edgeCover(n)))

Enter Number of Vertices : 5
3


In [15]:
global N
N = 4

def printSolution(board):
    for i in range(N):
        for j in range(N):
            print(board[i][j],end=" ")
        print()

def isSafe(board,row,col):
    for i in range(col):
        if board[row][i]==1:
            return False
    for i,j in zip(range(row,-1,-1),range(col,-1,-1)):
        if board[i][j] == 1:
            return False
    for i,j in zip(range(row,N,1),range(col,-1,-1)):
        if board[i][j] == 1:
            return False
    return True

def solveNQUtil(board,col):
    if col>=N:
        return True
    for row in range(N):
        if isSafe(board,row,col):
            board[row][col]=1
            
            if solveNQUtil(board,col+1)==True:
                return True
            
            board[row][col]=0
            
    return False

def solveNQ():
    board = [[0,0,0,0],
             [0,0,0,0],
             [0,0,0,0],
             [0,0,0,0]
            ]
    if solveNQUtil(board,0)==False:
        print("No Solution")
        return False
    printSolution(board)
    return True

solveNQ()

0 0 1 0 
1 0 0 0 
0 0 0 1 
0 1 0 0 


True

In [16]:
                                         #File Handling
#inputing text into file
a = input("Enter the text : ")
try:
    with open('text.txt','w') as text:
        text.write(a)
except Exception as e:
    print("There is a problem",str(e))

Enter the text : Hello there


In [18]:
#Convert text to upper case
with open('text.txt','r') as text:
    with open('output.txt','a') as output:
        for line in text:
            output.write(line.upper())

In [2]:
#Saving Dictionary in text file
myDic = {'Name':'Siva Vimel Rajhen',
        'Age':21,
        'Aim':'AI Dev'}

with open('file.txt','w') as file:
    for key,value in myDic.items():
        file.write('%s:%s\n' % (key,value))

In [6]:
#Find repeating word in a file
a = input("Enter The Text : " )
with open('sample.txt','w') as sample:
    sample.write(a)

file = open('sample.txt','r')
freq_w=''
frequency = 0 
words=[]
for line in file:
    line_word = line.lower().split()
    for w in line_word:
        words.append(w)

for i in range(0,len(words)):
    count = 1
    for j in range(i+1,len(words)):
        if(words[i]==words[j]):
            count=count+1
    if count>frequency:
        frequency = count
        freq_w = words[i]

print("Most Frequent Word : ",freq_w)
print("Frequency : ",frequency)
file.close()

Enter The Text : hello hello bro bro i am siva siva siva
Most Frequent Word :  siva
Frequency :  3


In [7]:
#Read Specific Lines
file = open('line.txt','r')
content = file.readlines()

print("Tenth Line : ")
print(content[9])

print("First Three Lines : ")
print(content[0:3])

Tenth Line : 
This is line 10
First Three Lines : 
['This is line 1\n', 'This is line 2\n', 'This is line 3\n']


In [9]:
                                   #CSV
#To update csv column
import pandas as pd
df = pd.read_csv('csv1.csv')
df.loc[5,'Name'] = 'Siva Vimel'

df.to_csv('csv1.csv',index=False)
print(df)

   Unnamed: 0.3  Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0  Sno  \
0             0             0             0           0    1   
1             1             1             1           1    2   
2             2             2             2           2    3   
3             3             3             3           3    4   
4             4             4             4           4    5   
5             5             5             5           5    6   
6             6             6             6           6    7   
7             7             7             7           7    8   

   Regristation Number                     Name     RollNo Status  
0             11913907              Molly Singh  RK19TSA01      P  
1             11918698      Vaishnavi choudhary  RK19TSA02      P  
2             12000722            Animesh Singh  RK19TSA03      P  
3             12003178              Yash Panwar  RK19TSA04      P  
4             12005300           Kallem Kruthik  RK19TSA05      P  
5             1

In [16]:
#OS Startup time
import os
t = os.popen('uptime -p').read()[:-1]
print(t)

up 46 minutes


In [17]:
#Get Background running apps
import os
output = os.popen('wmic process get description,processid').read()
print(output)

  File "/usr/local/bin/wmic", line 84
    print 'CLASS: %s' % classObject.getClassName()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?


In [22]:
#Modification Time of a file
import os
import time
path = r"sample.txt"
t_m = os.path.getmtime(path)
m_ti = time.ctime(t_m)
t_obj = time.strptime(m_ti)
T_stmp = time.strftime("%Y-%m-%d %H:%M:%S",t_obj)
print(f"Modified on : {T_stmp}")

Modified on : 2023-02-02 21:49:37


In [31]:
                                 #Empty Array
import numpy as np

em = np.empty((3,4),dtype=int)
print("Empty Array : ")
print(em)

Empty Array : 
[[94573171447042              0   206158430253   193273528370]
 [  214748364848   210453397588   249108103222   231928234034]
 [  223338299450   197568495665   206158430258   386547056692]]


In [34]:
                                  #Full Array
import numpy as np
full = np.full([3,3],55,dtype=int)
print("Full Array : ")
print(full)

Full Array : 
[[55 55 55]
 [55 55 55]
 [55 55 55]]


In [35]:
                              #Replace Element in Array
import numpy as np
a = np.array([10,20,30,40,50])
print("Given Array : ")
print(a)
a[a>10]=0
print("Replaced Array : ")
print(a)

Given Array : 
[10 20 30 40 50]
Replaced Array : 
[10  0  0  0  0]


In [38]:
                              #Pandas DataFrame with 2D-List
import pandas as pd
lst = [['Siva',21],['Papa',21],['Yoyo',12],['Sun',121]]

df = pd.DataFrame(lst,columns=["Name","Age"])
print(df)

   Name  Age
0  Siva   21
1  Papa   21
2  Yoyo   12
3   Sun  121


In [43]:
                              #Iterate over rows in DataFrame
import pandas as pd
lst = [['Siva',21],['Papa',21],['Yoyo',12],['Sun',121]]

df = pd.DataFrame(lst,columns=["Name","Age"])
print("Orginal DataFrame")
print(df)

print("Iterrated : ")
for index,row in df.iterrows():
    print(row['Name'],row['Age'])

Orginal DataFrame
   Name  Age
0  Siva   21
1  Papa   21
2  Yoyo   12
3   Sun  121
Iterrated : 
Siva 21
Papa 21
Yoyo 12
Sun 121


In [46]:
                                    #Series From Array
import pandas as pd
import numpy as np

a = np.array(['a','b','c','d'])

df = pd.Series(a,index=[1001,1002,1003,1004])
print(df)

1001    a
1002    b
1003    c
1004    d
dtype: object


In [57]:
                                    #Time-Series Manipulation
import pandas as pd
import numpy as np

range1 = pd.date_range(start='1/1/2019',end='1/08/2019',freq='Min')
df = pd.DataFrame(range1,columns = ['Date'])

df['Data'] = np.random.randint(0,100,size=(len(range1)))
print(df.head(10))

                 Date  Data
0 2019-01-01 00:00:00    79
1 2019-01-01 00:01:00    76
2 2019-01-01 00:02:00    57
3 2019-01-01 00:03:00    78
4 2019-01-01 00:04:00    84
5 2019-01-01 00:05:00    94
6 2019-01-01 00:06:00     6
7 2019-01-01 00:07:00    74
8 2019-01-01 00:08:00    48
9 2019-01-01 00:09:00    91


In [ ]:
                                          #TKinter

In [9]:
#GUI Marksheet

import tkinter as tk
master = tk.Tk()
master.title("MARKSHEET")
#master.config(bg="black")
master.geometry("700x250")

e1 = tk.Entry(master)
e2 = tk.Entry(master)
e3 = tk.Entry(master)
e4 = tk.Entry(master)
e5 = tk.Entry(master)
e6 = tk.Entry(master)
e7 = tk.Entry(master)

def display():
    total = 0
    if e4.get() == 'A':
        tk.Label(master,text="40").grid(row=3,column=4)
        total += 40
    if e4.get() == 'B':
        tk.Label(master,text="36").grid(row=3,column=4)
        total+=36
    if e5.get() == 'A':
        tk.Label(master,text="40").grid(row=4,column=4)
        total+=40
    if e5.get() == 'B':
        tk.Label(master,text="36").grid(row=4,column=4)
        total+=36
    if e6.get() == 'A':
        tk.Label(master,text="40").grid(row=5,column=4)
        total+=40
    if e6.get() == 'B':
        tk.Label(master,text="36").grid(row=5,column=4)
        total+=36
    if e7.get() == 'A':
        tk.Label(master,text="40").grid(row=6,column=4)
        total+=40
    if e7.get() == 'B':
        tk.Label(master,text="36").grid(row=6,column=4)
        total +=36
    tk.Label(master,text=str(total)).grid(row=7,column=4)
    tk.Label(master,text=str(total/15)).grid(row=8,column=4)

tk.Label(master,text="Name").grid(row=0,column=0)
tk.Label(master,text="Reg.No").grid(row=0,column=3)
tk.Label(master,text="Roll.No").grid(row=1,column=0)

tk.Label(master,text="Sr.No").grid(row=2,column=0)
tk.Label(master,text="1").grid(row=3,column=0)
tk.Label(master,text="2").grid(row=4,column=0)
tk.Label(master,text="3").grid(row=5,column=0)
tk.Label(master,text="4").grid(row=6,column=0)

tk.Label(master,text="Subject").grid(row=2,column=1)
tk.Label(master,text="CS 201").grid(row=3,column=1)
tk.Label(master,text="CS 202").grid(row=4,column=1)
tk.Label(master,text="MA 201").grid(row=5,column=1)
tk.Label(master,text="EC 201").grid(row=6,column=1)

tk.Label(master,text="Grade").grid(row=2,column=2)
e4.grid(row=3,column=2)
e5.grid(row=4,column=2)
e6.grid(row=5,column=2)
e7.grid(row=6,column=2)

tk.Label(master,text="Credit Obtained").grid(row=2,column=3)
tk.Label(master,text="4").grid(row=3,column=3)
tk.Label(master,text="4").grid(row=4,column=3)
tk.Label(master,text="3").grid(row=5,column=3)
tk.Label(master,text="4").grid(row=6,column=3)

e1.grid(row=0,column=1)
e2.grid(row=0,column=4)
e3.grid(row=1,column=1)

button1 = tk.Button(master,text="Submit",bg="green",command=display)
button1.grid(row=8,column=1)

tk.Label(master,text="Total Credit").grid(row=7,column=3)
tk.Label(master,text="SGPA").grid(row=8,column=3)

master.mainloop()


In [14]:
                                       #BeautifulSoup
#Geting content from webpage
import urllib.request
from bs4 import BeautifulSoup

urllib.request.urlretrieve("https://www.geeksforgeeks.org/python-programming-language/", "/home/anonimouz/text_file.txt")

file = open('text_file.txt','r')
content = file.read()
soup=BeautifulSoup(content,'html.parser')

f = open('test1.txt','w')
for data in soup.find_all('p'):
    sum = data.get_text()
    f.writelines(sum)
    
f.close()

text = open('test1.txt','r')
contents = text.readlines()
print(contents)


['Python is a high-level, general-purpose and a very popular programming language. Python programming language (latest Python 3) is being used in web development, Machine Learning applications, along with all cutting edge technology in Software Industry. Python Programming Language is very well suited for Beginners, also for experienced programmers with other programming languages like C++ and Java.This specially designed Python tutorial will help you learn Python Programming Language in most efficient way, with the topics from basics to advanced (like Web-scraping, Django, Deep-Learning, etc.) with examples.Below are some facts about Python Programming Language:Recent Articles on Python !Python Programming ExamplesPython Output & Multiple Choice Questions\xa0Basics, Input/Output, Data Types, Variables, Operators, Control Flow, Functions, Object Oriented Concepts, Exception Handling, Python Collections, Django Framework, Data Analysis, Numpy, Pandas, Machine Learning with Python, Pytho

In [22]:
#checking url status
from urllib.request import urlopen
from urllib.error import *

try:
    html = urlopen("https://www.geeksforgeeks.org/python-programming-language/")
except HTTPError as e:
    print("HTTP Error",e)
except URLError as e:
    print("URL Error",e)
else:
    print("Found")

Found


In [27]:
                                          #Wikipedia
#get summary of content
import wikipedia
wikipedia.summary('Python (programming language)')

'Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation.Python is dynamically typed and garbage-collected. It supports multiple programming paradigms, including structured (particularly procedural), object-oriented and functional programming. It is often described as a "batteries included" language due to its comprehensive standard library.Guido van Rossum began working on Python in the late 1980s as a successor to the ABC programming language and first released it in 1991 as Python 0.9.0. Python 2.0 was released in 2000. Python 3.0, released in 2008, was a major revision not completely backward-compatible with earlier versions. Python 2.7.18, released in 2020, was the last release of Python 2.Python consistently ranks as one of the most popular programming languages.'

In [30]:
#Get page content
import wikipedia
wikipedia.page('Python (programming language)').content

'Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation.Python is dynamically typed and garbage-collected. It supports multiple programming paradigms, including structured (particularly procedural), object-oriented and functional programming. It is often described as a "batteries included" language due to its comprehensive standard library.Guido van Rossum began working on Python in the late 1980s as a successor to the ABC programming language and first released it in 1991 as Python 0.9.0. Python 2.0 was released in 2000. Python 3.0, released in 2008, was a major revision not completely backward-compatible with earlier versions. Python 2.7.18, released in 2020, was the last release of Python 2.Python consistently ranks as one of the most popular programming languages.\n\n\n== History ==\n\nPython was conceived in the late 1980s by Guido van Rossum at Centrum Wiskunde & Informatica (CWI) in 

In [31]:
#Extract images from wikipedia
import wikipedia
wikipedia.page('Python (programming language)').images

['https://upload.wikimedia.org/wikipedia/commons/3/31/Free_and_open-source_software_logo_%282009%29.svg',
 'https://upload.wikimedia.org/wikipedia/commons/9/94/Guido_van_Rossum_OSCON_2006_cropped.png',
 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Octicons-terminal.svg',
 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg',
 'https://upload.wikimedia.org/wikipedia/commons/c/c4/Python_3._The_standard_type_hierarchy-en.svg',
 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Python_Powered.png',
 'https://upload.wikimedia.org/wikipedia/commons/d/df/Wikibooks-logo-en-noslogan.svg',
 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Wikibooks-logo.svg',
 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Wikidata-logo.svg',
 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Wikiquote-logo.svg',
 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Wikiversity_logo_2017.svg',
 'https://upload.wikimedia.org/wikipedia/en/4/4a/Commons-logo.svg',
 'ht

In [32]:
#Get url of topic
import wikipedia
wikipedia.page('sunflower').url

'https://en.wikipedia.org/wiki/Helianthus'

In [33]:
#List of categories of articles
import wikipedia
wikipedia.page('sunflower').categories

['All articles with unsourced statements',
 "Articles with 'species' microformats",
 'Articles with short description',
 'Articles with unsourced statements from June 2022',
 'Asteraceae genera',
 'CS1 maint: others',
 'Crops',
 'Crops originating from indigenous Americans',
 'Flora of North America',
 'Helianthus',
 'Short description is different from Wikidata',
 'Taxa named by Carl Linnaeus',
 'Taxonbars with 25–29 taxon IDs',
 'Webarchive template wayback links',
 'Wikipedia articles needing clarification from October 2022']

In [34]:
#List of all links to an article
import wikipedia
wikipedia.page('sunflower').links

['Agricultural Research Service',
 'Alabama',
 'Annual plant',
 'Anthesis',
 'Arizona',
 'Arkansas',
 'Asteraceae',
 'Asterales',
 'Asterids',
 'Asteroideae',
 'Australian Plant Name Index',
 'Baja California (state)',
 'Baja California Sur',
 'Bibcode (identifier)',
 'Caducous',
 'California',
 'Carl Linnaeus',
 'Catalogue of Life',
 'Central America',
 'Chihuahua (state)',
 'Chile',
 'Coahuila',
 'Colorado',
 'Common sunflower',
 'Connecticut',
 'Cultivar',
 'Cultivars',
 'Doi (identifier)',
 'EPPO Code',
 'Encyclopedia of Life',
 'Endangered',
 'Endangered Species Act',
 'Endogeny (biology)',
 'Eudicots',
 "Fermat's spiral",
 'Fibonacci number',
 'FloraBase',
 'Flora of Australia',
 'Flora of China (series)',
 'Flora of North America',
 'Florets',
 'Florida',
 'Florivore',
 'Flourensia thurifera',
 'Flowering plant',
 'French Guiana',
 'Gahkuch',
 'Genus',
 'Georgia (U.S. state)',
 'Germplasm Resources Information Network',
 'Global Biodiversity Information Facility',
 'Glossary of 

In [36]:
#Set Language
import wikipedia
wikipedia.set_lang('ml')
wikipedia.summary('sunflower')

'ഒരു വാർഷിക സസ്യമാണ് സൂര്യകാന്തി. ഇവയുടെ പൂവിന്റെ തണ്ട് 3 മീറ്റർ ഉയരത്തിൽ വരെ വളരാറുണ്ട്. 30 സെന്റീമീറ്റർ വരെ വ്യാസത്തിൽ കാണപ്പെടുന്ന പൂവിൽ വലിയ വിത്തുകൾ കാണാം. ജന്മദേശം അമേരിക്കയായ ഈ സസ്യത്തിന്റെ കുടുംബം “ആസ്റ്ററാസീയേ“(Asteraceae) ആണ്\u200c.\nഎണ്ണയോടൊപ്പം അമേരിക്കയിൽ നിന്നും 16ആം നൂറ്റാണ്ടിൽ യൂറോപ്പിലേക്ക് സൂര്യകാന്തി വിത്തുകൾ കൊണ്ടുവന്നു. സൂര്യകാന്തി പാചക എണ്ണ വളരെ പ്രചാരം നേടി. നാരുകൾ കൂടുതലുള്ളതുകൊണ്ട് പേപ്പർ നിർമ്മാണത്തിനും കാലിത്തീറ്റാ മിശ്രിതമായും സൂര്യകാന്തി ഇല ഉപയോഗിക്കാം.'

In [68]:
                                         #Webscrapping

In [26]:
                                       #LinkedIn WebCrawler Bot

In [1]:
#LinkedIn Scrapping 

import time
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("https://linkedin.com/uas/login")
time.sleep(5)

username = driver.find_element(By.ID,"username")
username.send_keys("iamanonimouzanoni@gmail.com")

pword = driver.find_element(By.ID,"password")
pword.send_keys("9747957715")

driver.find_element(By.XPATH,"//button[@type='submit']").click()

profile_url = "https://www.linkedin.com/in/subiksha-sathiasai-9b3600195/"
driver.get(profile_url)

#Scrolling Script

start = time.time()
initialScroll = 0
finalScroll = 1000

while(True):
    driver.execute_script(f"window.scrollTo({initialScroll},{finalScroll})")
    initialScroll = finalScroll
    finalScroll+=1000
    time.sleep(3)
    
    end=time.time()
    if round(end-start)>10:
        break
        
################
#getting page source
src = driver.page_source
soup = BeautifulSoup(src,'lxml')

#getting page introduction
intro = soup.find('div',{'class':'pv-text-details__left-panel'})

#Extracting HTML
name_loc  = intro.find('h1')
name = name_loc.get_text().strip()

work_loc = intro.find("div",{'class':'text-body-medium'})
work = work_loc.get_text().strip()

connection_loc = intro.find_all("span", {'class': 'text-body-small'})
connection = connection_loc[0].get_text().strip()

location_loc = f"/html/body/div[5]/div[3]/div/div/div[2]/div/div/main/section[1]/div[2]/div[2]/div[2]/span[1]"
location = driver.find_element(By.XPATH,location_loc)

print("Name : ",name)
print("Works As : ",work)
print("Connection : ",connection)
print("Location : ",location.text)

#Going to jobs page
jobs = driver.find_element(By.XPATH,"//*[@id='global-nav']/div/nav/ul/li[3]/a")
jobs.click()

Enter The URL : https://www.linkedin.com/in/subiksha-sathiasai-9b3600195/
Name :  SUBIKSHA SATHIASAI
Works As :  Student | Web Developer | AI
Connection :  1st degree connection
  

    1st
Location :  Salem, Tamil Nadu, India


In [77]:
#Download File
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("https://demo.automationtesting.in/FileDownload.html")

driver.find_element(By.ID,"textbox").send_keys("Hello")
driver.find_element(By.ID,"createTxt").click()
driver.find_element(By.XPATH,"//*[@id='link-to-download']").click() 

In [90]:
#Count Number of links in webpage
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("https://www.geeksforgeeks.org/")

links = driver.find_elements(By.TAG_NAME,"a")
print(len(links))

782


In [92]:
#Search for text in page
from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("https://www.geeksforgeeks.org/")

src = driver.page_source
text = "Beauty"
text2 = "geeks"

print(text in src)
print(text2 in src)

False
True
